-- Create OTP codes table for Resend email verification
CREATE TABLE IF NOT EXISTS otp_codes (
  id BIGSERIAL PRIMARY KEY,
  email TEXT NOT NULL,
  otp TEXT NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  CONSTRAINT otp_codes_email_otp_unique UNIQUE(email, otp)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS otp_codes_email_idx ON otp_codes(email);
CREATE INDEX IF NOT EXISTS otp_codes_expires_at_idx ON otp_codes(expires_at);
CREATE INDEX IF NOT EXISTS otp_codes_used_idx ON otp_codes(used);

-- Enable Row Level Security
ALTER TABLE otp_codes ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Allow inserts (new OTP generation)
CREATE POLICY "Allow insert otp codes" ON otp_codes
  FOR INSERT WITH CHECK (true);

-- RLS Policy: Allow reads on own email's OTP codes
CREATE POLICY "Allow read otp codes" ON otp_codes
  FOR SELECT USING (true);

-- RLS Policy: Allow updates (mark as used)
CREATE POLICY "Allow update otp codes" ON otp_codes
  FOR UPDATE USING (true);

-- Optional: Clean up expired OTPs daily
-- This would be handled by a scheduled function or cron job
COMMENT ON TABLE otp_codes IS 'Stores OTP codes generated by Resend email service. OTPs expire after 10 minutes.';
